// Regenerates agent-runtime/src/shared/abi.generated.ts from Foundry's build
// output, so no ABI is ever written by hand. Run after `forge build`:
//   npm run gen:abi
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const abiOf = (name) => JSON.parse(readFileSync(join(root, 'out', `${name}.sol`, `${name}.json`), 'utf8')).abi

const out = `// GENERATED by scripts/gen-abi.mjs from Foundry build output (out/). Do not edit.
// Regenerate with: forge build && npm run gen:abi

export const AGENT_ECO_ABI = ${JSON.stringify(abiOf('AgentEco'), null, 2)} as const

export const MOCK_USDT_ABI = ${JSON.stringify(abiOf('MockUSDT'), null, 2)} as const
`

const target = join(root, 'agent-runtime', 'src', 'shared', 'abi.generated.ts')
writeFileSync(target, out)
console.log(`wrote ${target}`)
